import pandas as pd
import numpy as np

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generate technical features and target variable from historical price data.

    Parameters:
    df (pandas.DataFrame): A DataFrame containing at least a 'close' column 
                           representing closing prices.

    Returns:
    pandas.DataFrame: A DataFrame with additional feature columns:
        - 'return': Daily percentage change of the closing price.
        - 'rsi': Relative Strength Index over 14 days.
        - 'macd': 12-day EMA minus 26-day EMA.
        - 'macd_signal': 9-day EMA of the MACD line.
        - 'macd_histogram': MACD line minus signal line.
        - 'ma_3/5/10/20/50': Simple moving averages over respective periods.
        - 'bb_upper/lower/width': Bollinger Bands based on 20-day MA and std deviation.
        - 'adx': Average Directional Index over 14 days.
        - '+di'/'-di': Positive and negative directional indicators.
        - 'target_return': Next-period return (shifted by -1).

    Notes:
    - Rows containing NaN values generated by rolling calculations
      and shifting are removed before returning the DataFrame.
    - The function modifies the input DataFrame in place.
    """
    df["return"] = df["close"].pct_change()

    delta_close = df["close"].diff()
    gain = delta_close.clip(lower=0)
    loss = delta_close.clip(upper=0) * -1
    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()
    rs = avg_gain / avg_loss
    df["rsi"] = 100 - 100/(1 + rs)

    df["macd"] = df["close"].ewm(span=12).mean() - df["close"].ewm(span=26).mean()
    df["macd_signal"] = df["macd"].ewm(span=9).mean()
    df["macd_histogram"] = df["macd"] - df["macd_signal"]

    df["ma_3"] = df["close"].rolling(3).mean()
    df["ma_5"] = df["close"].rolling(5).mean()
    df["ma_10"] = df["close"].rolling(10).mean()
    df["ma_20"] = df["close"].rolling(20).mean()
    df["ma_50"] = df["close"].rolling(50).mean()

    std_20 = df["close"].rolling(20).std()
    df["bb_upper"] = df["ma_20"] + (2 * std_20)
    df["bb_lower"] = df["ma_20"] - (2 * std_20)
    df["bb_width"] = df["bb_upper"] - df["bb_lower"]

    high_diff = df["high"].diff()
    low_diff = df["low"].diff() * -1
    df["+dm"] = np.where((high_diff > low_diff) & (high_diff > 0), high_diff, 0)
    df["-dm"] = np.where((low_diff > high_diff) & (low_diff > 0), low_diff, 0)
    df["tr"] = pd.concat([
        df["high"] - df["low"],
        (df["high"] - df["close"].shift(1)).abs(),
        (df["low"] - df["close"].shift(1)).abs()
    ], axis=1).max(axis=1)
    df["atr"] = df["tr"].rolling(14).mean()
    df["+di"] = (df["+dm"].rolling(14).mean()) * 100/df["atr"]
    df["-di"] = (df["-dm"].rolling(14).mean()) * 100/df["atr"]
    df["dx"] = 100 * (abs(df["+di"] - df["-di"]) / (df["+di"] + df["-di"]))
    df["adx"] = df["dx"].rolling(14).mean()

    df["target_return"] = df["return"].shift(-1)

    df = df.dropna()
    
    return df
