import pandas as pd

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generate technical features and target variable from historical price data.

    Parameters:
    df (pandas.DataFrame): A DataFrame containing at least a 'close' column 
                           representing closing prices.

    Returns:
    pandas.DataFrame: A DataFrame with additional feature columns:
        - 'return': Percentage change of the closing price.
        - 'volatility': 5-period rolling standard deviation of returns.
        - 'ma_3': 3-period moving average of the closing price.
        - 'ma_5': 5-period moving average of the closing price.
        - 'ma_10': 10-period moving average of the closing price.
        - 'ma_20': 20-period moving average of the closing price.
        - 'ma_50': 50-period moving average of the closing price.
        - 'rsi': Relative Strength Index (14 day period)
        - 'target_return': Next-period return (shifted by -1),
                           typically used as a prediction target.

    Notes:
    - Rows containing NaN values generated by rolling calculations
      and shifting are removed before returning the DataFrame.
    - The function modifies the input DataFrame in place.
    """
    df["return"] = df["close"].pct_change()
    df["volatility"] = df["return"].rolling(5).std()
    delta_close = df["close"].diff()
    gain = delta_close.clip(lower=0)
    loss = delta_close.clip(upper=0) * -1
    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()
    rs = avg_gain / avg_loss
    df["rsi"] = 100 - 100/(1 + rs)
    df["macd"] = df["close"].ewm(span=12).mean() = df["close"].ewm(span=26).mean()
    df["macd_signal"] = df["macd"].ewm(span=9).mean()
    df["macd_histogram"] = df["macd"] - df["macd_signal"]
    df["ma_3"] = df["close"].rolling(3).mean()
    df["ma_5"] = df["close"].rolling(5).mean()
    df["ma_10"] = df["close"].rolling(10).mean()
    df["ma_20"] = df["close"].rolling(20).mean()
    df["ma_50"] = df["close"].rolling(50).mean()
    
    df["target_return"] = df["return"].shift(-1)
    
    df = df.dropna()

    return df
